name: Node CI

on:
  push:
    branches:
      - develop

jobs:

  install_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - name: npm install
      run: npm install

    - name: npm run build
      run: npm run build